In [1]:
import pandas as pd
import numpy as np

yield_df = pd.read_csv("data/raw/yield.csv")
temp_df = pd.read_csv("data/raw/temp.csv")
rain_df = pd.read_csv("data/raw/rainfall.csv")
pest_df = pd.read_csv("data/raw/pesticides.csv")

In [ ]:
yield_df.columns = yield_df.columns.str.strip()
temp_df.columns = temp_df.columns.str.strip()
rain_df.columns = rain_df.columns.str.strip()
pest_df.columns = pest_df.columns.str.strip()

# Yield
yield_df = yield_df.rename(columns={
    "Area": "country",
    "Item": "crop",
    "Year": "year",
    "Value": "yield"
})

# Temp
temp_df = temp_df.rename(columns={
    "country": "country",
    "year": "year"
})

# Rain
rain_df = rain_df.rename(columns={
    "Area": "country",
    "Year": "year",
    "average_rain_fall_mm_per_year": "rainfall"
})

# Pesticides
pest_df = pest_df.rename(columns={
    "Area": "country",
    "Year": "year",
    "Value": "pesticides"
})

In [3]:
yield_df = yield_df[["country", "crop", "year", "yield"]]
temp_df = temp_df[["country", "year", "avg_temp"]]
rain_df = rain_df[["country", "year", "rainfall"]]
pest_df = pest_df[["country", "year", "pesticides"]]

In [4]:
temp_df["avg_temp"] = pd.to_numeric(temp_df["avg_temp"], errors="coerce")
rain_df["rainfall"] = pd.to_numeric(rain_df["rainfall"], errors="coerce")
pest_df["pesticides"] = pd.to_numeric(pest_df["pesticides"], errors="coerce")
yield_df["yield"] = pd.to_numeric(yield_df["yield"], errors="coerce")

In [5]:
temp_df["avg_temp"] = temp_df["avg_temp"].fillna(temp_df["avg_temp"].mean())
rain_df["rainfall"] = rain_df["rainfall"].fillna(rain_df["rainfall"].median())
pest_df["pesticides"] = pest_df["pesticides"].fillna(0)

In [6]:
df = yield_df.merge(temp_df, on=["country", "year"], how="left")
df = df.merge(rain_df, on=["country", "year"], how="left")
df = df.merge(pest_df, on=["country", "year"], how="left")

In [7]:
print(df.shape)
df.head()

(109366, 7)

       country   crop  year  yield  avg_temp  rainfall  pesticides
0  Afghanistan  Maize  1961  14000     14.23       NaN         NaN
1  Afghanistan  Maize  1962  14000     14.10       NaN         NaN
2  Afghanistan  Maize  1963  14260     15.01       NaN         NaN
3  Afghanistan  Maize  1964  14257     13.73       NaN         NaN
4  Afghanistan  Maize  1965  14400     13.90       NaN         NaN

In [8]:
df = df.dropna()
print(df.shape)

(28248, 7)

In [ ]:
import os

file_path = "data/processed/master_dataset.csv"

os.makedirs(os.path.dirname(file_path), exist_ok=True)

df.to_csv(file_path, index=False)
print("Saved Successfully as master_dataset.csv")

Saved Successfully as master_dataset.csv

In [11]:
df.info()
df.head()
df.describe()

<class 'pandas.DataFrame'>
Index: 28248 entries, 253 to 109362
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     28248 non-null  str
 1   crop        28248 non-null  str
 2   year        28248 non-null  int64
 3   yield       28248 non-null  int64
 4   avg_temp    28248 non-null  float64
 5   rainfall    28248 non-null  float64
 6   pesticides  28248 non-null  float64
dtypes: float64(3), int64(2), str(2)
memory usage: 1.7 MB

               year          yield      avg_temp      rainfall     pesticides
count  28248.000000   28248.000000  28248.000000  28248.000000   28248.000000
mean    2001.541950   77047.863282     20.543722   1149.026444   37069.136973
std        7.052997   84950.194454      6.311828    709.739653   59954.787836
min     1990.000000      50.000000      1.300000     51.000000       0.040000
25%     1995.000000   19918.750000     16.710000    593.000000    1695.710000
50%     2001.000000   38295.000000     21.510000   1083.000000   17517.760000
75%     2008.000000  104598.250000     26.000000   1668.000000   48687.880000
max     2013.000000  501412.000000     30.650000   3240.000000  367778.000000